### ISSUE TITLE
cordova build error after adding plugin

### ISSUE THREAD

**Issue by maulpets** [swayangjit/cordova-plugin-play-installreferrer#10]
[INF] [shellscript] > Task :CordovaLib:bundleLibCompileToJarDebug UP-TO-DATE
[INF] [shellscript] Note: Some input files use or override a deprecated API.
[INF] [shellscript] Note: Recompile with -Xlint:deprecation for details.
[INF] [shellscript] 
[INF] [shellscript] > Task :app:compileDebugJavaWithJavac FAILED
[INF] [shellscript] C:\Users\maulp\Documents\web-projects\packaged-pwa\packaged_pwa\cordova\platforms\androi.annotation does not exist
[INF] [shellscript] import android.support.annotation.Nullable;
[INF] [shellscript]                                  ^
[INF] [shellscript] C:\Users\maulp\Documents\web-projects\packaged-pwa\packaged_pwa\cordova\platforms\androi
[INF] [shellscript]     private void handleReferrer(@Nullable ReferrerDetails response, int responseCode) '{
[INF] [shellscript]                                  ^
[INF] [shellscript]   symbol:   class Nullable
[INF] [shellscript]   location: class PlayStoreInstallReferrerImpl
[INF] [shellscript] Note: C:\Users\maulp\Documents\web-projects\packaged-pwa\packaged_pwa\cordova\platforms\erations.
[INF] [shellscript] Note: Recompile with -Xlint:unchecked for details.
[INF] [shellscript] 2 errors
[INF] [shellscript]
[INF] [shellscript] FAILURE: Build failed with an exception.
[INF] [shellscript]
[INF] [shellscript] * What went wrong:
[INF] [shellscript] Execution failed for task ''':app:compileDebugJavaWithJavac'''.
[INF] [shellscript] > Compilation failed; see the compiler error output for details.

**Comment by maulpets** [comment]
getting this error whenever i add this plugin and builds fine once i remove it

**Comment by swayangjit** [comment]
@maulpets First of all thank you for using the library. I have just published a new version and pushed the updated code to the master branch. You can use it and let me know if the issue is fixed or not.

**Comment by maulpets** [comment]
I actually moved to a different plugin shortly after this comment

**Comment by swayangjit** [comment]
@maulpets Ok Thanks for using.
